version: 4.0.0.{build}

platform:
    - Win32
    - x64

configuration:
    - Debug
    - Release

matrix:
    fast_finish: true

before_build:
    - if "%platform%"=="Win32" cmake -G"Visual Studio 10"
    - if "%platform%"=="64" cmake -G"Visual Studio 10 Win64"

build:
    project: SOCI.sln

test_script:
    - ctest -C %configuration% -VV
